version: '3'
services:
  redpanda:
    # MUDANÇA AQUI: Usando a imagem do Docker Hub
    image: redpandadata/redpanda:v23.1.2
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --kafka-addr 0.0.0.0:9092
      - --advertise-kafka-addr localhost:9092
    ports:
      - "9092:9092"

  schema-registry:
    image: apicurio/apicurio-registry-mem:2.4.4.Final
    container_name: apicurio-avro-registry
    ports:
      - "8084:8080"
    environment:
      # Opcional: Habilita log de nível DEBUG se precisar ver o registro acontecendo
      QUARKUS_LOG_LEVEL: INFO
    # ---------------------------------------
  postgres:
    image: postgres:15
    container_name: postgres-saga
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
